In [1]:
from iterative_searcher import IterativeSearcher

from Qommunity.samplers.hierarchical.advantage_sampler import AdvantageSampler
from Qommunity.searchers.hierarchical_community_searcher import (
    HierarchicalCommunitySearcher,
)

import networkx as nx
import numpy as np

In [2]:
import os


dir = f"output/"
os.makedirs(os.path.dirname(dir), exist_ok=True)

In [3]:
G = nx.karate_club_graph()

### Hierarchical

#### Basic usage

- Example of Advantage sampler usage with clique embedding:

In [4]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=True)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

In [5]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-karate")

100%|██████████| 5/5 [00:42<00:00,  8.46s/it]

CPU times: total: 10.4 s
Wall time: 42.3 s


In [6]:
communities

array([list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]])],
      dtype=object)

In [7]:
modularities

array([0.44018103, 0.44018103, 0.44018103, 0.44018103, 0.44018103])

In [8]:
times

array([8.16759419, 8.09223485, 8.07377148, 8.91090727, 9.04090881])

- Example of Advantage sampler usage without standard embedding approach:

In [9]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=False)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

In [10]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-karate-2")

100%|██████████| 5/5 [01:15<00:00, 15.05s/it]

CPU times: total: 22.6 s
Wall time: 1min 15s


In [11]:
communities

array([list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]])],
      dtype=object)

In [12]:
modularities

array([0.44018103, 0.44018103, 0.44018103, 0.44018103, 0.44018103])

In [13]:
times

array([13.41400528, 14.40149069, 16.56365085, 14.69405484, 16.1404171 ])

#### Extended sampleset info
- contains communities, modularities, times, division trees and division modularities

In [15]:
sampleset = iterative_searcher.run_with_full_sampleset_info(
    num_runs=5, save_results=False
)

100%|██████████| 5/5 [01:13<00:00, 14.64s/it]


In [16]:
sampleset

rec.array([(list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]), 0.44018103, 11.34289932, list([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]], [[8, 14, 15, 18, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33], [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 16, 17, 19, 21]], [[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]]), list([0.0, 0.3998332115215232, 0.44018103109012197])),
           (list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]), 0.44018103, 16.56514549, list([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]], [[8, 14, 15, 18, 20, 22, 23, 24, 25, 26, 27, 

In [17]:
sampleset.communities

array([list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]])],
      dtype=object)

In [18]:
sampleset.modularity

array([0.44018103, 0.44018103, 0.44018103, 0.44018103, 0.44018103])

In [19]:
sampleset.time

array([11.34289932, 16.56514549, 16.06549668, 12.80480218, 16.40964603])

In [20]:
sampleset.division_modularities

array([list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197])], dtype=object)

## Regular

In [4]:
from Qommunity.samplers.regular.leiden_sampler import LeidenSampler
from Qommunity.searchers.community_searcher import CommunitySearcher
from iterative_searcher import IterativeSearcher

import networkx as nx

In [22]:
G = nx.karate_club_graph()

In [23]:
searcher = CommunitySearcher(LeidenSampler(G))
iterative_searcher = IterativeSearcher(searcher)

In [24]:
communities, modularities, times = iterative_searcher.run(num_runs=100)

100%|██████████| 100/100 [00:00<00:00, 366.07it/s]


In [25]:
modularities

array([0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490

In [26]:
times

array([0.00703931, 0.00100279, 0.00099945, 0.        , 0.00100017,
       0.        , 0.00101328, 0.00100017, 0.0010016 , 0.00100327,
       0.0010004 , 0.00099993, 0.00099659, 0.00099897, 0.00100112,
       0.00099945, 0.00099993, 0.00099897, 0.        , 0.00099897,
       0.0010004 , 0.00099897, 0.00100017, 0.00099969, 0.00100088,
       0.0010798 , 0.00100064, 0.00100017, 0.0010004 , 0.00200701,
       0.00099587, 0.00099993, 0.00100017, 0.        , 0.        ,
       0.00099921, 0.00099897, 0.        , 0.00099969, 0.        ,
       0.00099993, 0.        , 0.00100017, 0.        , 0.00100017,
       0.00099993, 0.0010004 , 0.00099993, 0.00099874, 0.00099897,
       0.0010004 , 0.        , 0.00099993, 0.        , 0.00101995,
       0.        , 0.00099993, 0.        , 0.0010004 , 0.00099921,
       0.00100183, 0.00099993, 0.00100303, 0.00099969, 0.        ,
       0.00100303, 0.00099993, 0.0010004 , 0.        , 0.        ,
       0.00100017, 0.0010004 , 0.00100517, 0.00100064, 0.00099

## Applying different resolution values

#### Hierarchical search

In [9]:
# same resolution values, no warnings
adv_sampler = AdvantageSampler(G, num_reads=100, resolution=1)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

%time communities, modularities, times = iterative_searcher.run(num_runs=2, score_resolution=1, save_results=False)

100%|██████████| 2/2 [00:26<00:00, 13.22s/it]

CPU times: total: 5.95 s
Wall time: 26.4 s


In [10]:
# different resolution values, warnings
adv_sampler = AdvantageSampler(G, num_reads=100, resolution=0.5)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

%time communities, modularities, times = iterative_searcher.run(num_runs=2, score_resolution=1, save_results=False)

100%|██████████| 2/2 [00:14<00:00,  7.06s/it]

CPU times: total: 5.91 s
Wall time: 14.1 s


In [11]:
# different resolution values, warnings
adv_sampler = AdvantageSampler(G, num_reads=100, resolution=1)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

%time communities, modularities, times = iterative_searcher.run(num_runs=2, score_resolution=0.5, save_results=False)

100%|██████████| 2/2 [00:27<00:00, 13.96s/it]

CPU times: total: 9.84 s
Wall time: 27.9 s


#### Regular search

In [5]:
from Qommunity.samplers.regular.louvain_sampler import LouvainSampler
from Qommunity.searchers.community_searcher import CommunitySearcher

In [6]:
# same resolution values, no warnings
searcher = CommunitySearcher(LouvainSampler(G))
iterative_searcher = IterativeSearcher(searcher)

%time communities, modularities, times = iterative_searcher.run(num_runs=100, save_results=False)

100%|██████████| 100/100 [00:00<00:00, 336.07it/s]

CPU times: total: 93.8 ms
Wall time: 306 ms


In [7]:
# different resolution values, warnings
searcher = CommunitySearcher(LouvainSampler(G, resolution=1))
iterative_searcher = IterativeSearcher(searcher)

%time communities, modularities, times = iterative_searcher.run(num_runs=5, score_resolution=0.5, save_results=False)

100%|██████████| 5/5 [00:00<00:00, 302.81it/s]

CPU times: total: 0 ns
Wall time: 20.5 ms


In [8]:
# different resolution values, warnings
searcher = CommunitySearcher(LouvainSampler(G, resolution=0.5))
iterative_searcher = IterativeSearcher(searcher)

%time communities, modularities, times = iterative_searcher.run(num_runs=5, score_resolution=1, save_results=False)

100%|██████████| 5/5 [00:00<00:00, 333.64it/s]

CPU times: total: 0 ns
Wall time: 19 ms


## Sample usecase

- Comparison of use_clique_embedding=True and False on a graph of 90 nodes

In [27]:
G = nx.powerlaw_cluster_graph(n=90, m=1, p=0.2)

In [28]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=True)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

In [29]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-powerlaw_90")

100%|██████████| 5/5 [02:49<00:00, 33.81s/it]

CPU times: total: 56.5 s
Wall time: 2min 49s


In [30]:
modularities

array([0.76833733, 0.7658124 , 0.76568615, 0.76757985, 0.77654337])

In [31]:
times

array([26.56346345, 33.01482844, 31.85231853, 31.55296373, 46.0393889 ])

In [32]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=False)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

In [33]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-powerlaw_90")

100%|██████████| 5/5 [09:26<00:00, 113.34s/it]

CPU times: total: 7min 10s
Wall time: 9min 26s


In [35]:
modularities

array([0.7439086 , 0.76164626, 0.7693473 , 0.75160965, 0.76448681])

In [36]:
times

array([162.53538895, 108.30013967,  99.48476887,  83.89677119,
       112.45903277])