In [8]:
from iterative_searcher import IterativeSearcher

from Qommunity.samplers.hierarchical.advantage_sampler import AdvantageSampler
from Qommunity.searchers.hierarchical_community_searcher import (
    HierarchicalCommunitySearcher,
)

import networkx as nx
import numpy as np

In [2]:
import os


dir = f"output/"
os.makedirs(os.path.dirname(dir), exist_ok=True)

In [3]:
G = nx.karate_club_graph()

### Hierarchical

#### Basic usage

- Example of Advantage sampler usage with clique embedding:

In [4]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=True)
iterative_searcher = IterativeSearcher(adv_sampler)

In [5]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-karate")

100%|██████████| 5/5 [00:53<00:00, 10.76s/it]

CPU times: total: 6.16 s
Wall time: 53.8 s


In [6]:
communities

array([list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]])],
      dtype=object)

In [7]:
modularities

array([0.44018103, 0.44018103, 0.44018103, 0.44018103, 0.44018103])

In [8]:
times

array([10.81358671, 10.74970031, 10.52897   , 10.99395394, 10.71682978])

- Example of Advantage sampler usage without standard embedding approach:

In [9]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=False)
iterative_searcher = IterativeSearcher(adv_sampler)

In [10]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-karate-2")

100%|██████████| 5/5 [01:08<00:00, 13.77s/it]

CPU times: total: 20.2 s
Wall time: 1min 8s


In [11]:
communities

array([list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]])],
      dtype=object)

In [12]:
modularities

array([0.44018103, 0.44018103, 0.44018103, 0.44018103, 0.44018103])

In [13]:
times

array([14.0335393 , 10.7783637 , 14.70217466, 14.35772491, 14.95646453])

#### Extended sampleset info
- contains communities, modularities, times, division trees and division modularities

In [14]:
sampleset = iterative_searcher.run_with_sampleset_info(
    num_runs=5, save_results=False
)

100%|██████████| 5/5 [01:03<00:00, 12.74s/it]


In [15]:
sampleset

rec.array([(list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]), 0.44018103, 12.31159449, list([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]], [[8, 14, 15, 18, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33], [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 16, 17, 19, 21]], [[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]]), list([0.0, 0.3998332115215232, 0.44018103109012197])),
           (list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]), 0.44018103, 10.77648926, list([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]], [[8, 14, 15, 18, 20, 22, 23, 24, 25, 26, 27, 

In [16]:
sampleset.communities

array([list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21], [23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]])],
      dtype=object)

In [17]:
sampleset.modularity

array([0.44018103, 0.44018103, 0.44018103, 0.44018103, 0.44018103])

In [18]:
sampleset.time

array([12.31159449, 10.77648926, 14.07307673, 12.51093316, 13.99912524])

In [19]:
sampleset.division_modularities

array([list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.440181031090122]),
       list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197])], dtype=object)

In [20]:
sampleset.division_tree

array([list([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]], [[8, 14, 15, 18, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33], [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 16, 17, 19, 21]], [[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]]),
       list([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]], [[8, 14, 15, 18, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33], [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 16, 17, 19, 21]], [[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]]),
       list([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]], [[0, 1, 2, 3, 4, 5, 6, 7, 9, 10

## Regular

In [1]:
from Qommunity.samplers.regular.leiden_sampler import LeidenSampler
from Qommunity.searchers.community_searcher import CommunitySearcher
from iterative_searcher import IterativeSearcher

import networkx as nx

In [2]:
G = nx.karate_club_graph()

In [3]:
leiden_sampler = LeidenSampler(G)
iterative_searcher = IterativeSearcher(leiden_sampler)

In [4]:
communities, modularities, times = iterative_searcher.run(num_runs=100, save_results=False)

  0%|          | 0/100 [00:00<?, ?it/s]

100%|██████████| 100/100 [00:00<00:00, 1269.10it/s]


In [5]:
modularities

array([0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490

In [6]:
times

array([0.00101042, 0.00100064, 0.        , 0.00108194, 0.        ,
       0.0009613 , 0.        , 0.        , 0.00100303, 0.00099754,
       0.00099921, 0.        , 0.00108624, 0.00094461, 0.        ,
       0.00099897, 0.        , 0.00099921, 0.00099802, 0.00100374,
       0.00091338, 0.00099659, 0.        , 0.        , 0.        ,
       0.00100899, 0.00101376, 0.00099325, 0.00090432, 0.00100207,
       0.00100803, 0.00099921, 0.00100136, 0.        , 0.        ,
       0.0009954 , 0.00100303, 0.00099993, 0.00100064, 0.00101423,
       0.00100803, 0.        , 0.00105238, 0.        , 0.00102258,
       0.        , 0.00099754, 0.        , 0.        , 0.00100017,
       0.        , 0.00094247, 0.        , 0.00105834, 0.        ,
       0.        , 0.        , 0.00089335, 0.00100422, 0.        ,
       0.00108624, 0.        , 0.0010047 , 0.        , 0.        ,
       0.0009985 , 0.        , 0.00099707, 0.        , 0.00101256,
       0.        , 0.        , 0.        , 0.        , 0.00099

## Sample usecase

- Comparison of use_clique_embedding=True and False on a graph of 90 nodes

In [10]:
G = nx.powerlaw_cluster_graph(n=90, m=1, p=0.2)

adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=True)
iterative_searcher = IterativeSearcher(adv_sampler)

In [11]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, save_results=False)

100%|██████████| 5/5 [03:10<00:00, 38.02s/it]

CPU times: total: 37.1 s
Wall time: 3min 10s


In [12]:
modularities

array([0.68753945, 0.68211084, 0.68324706, 0.6887388 , 0.69864916])

In [13]:
times

array([34.93011856, 35.20841479, 34.44822073, 41.9354403 , 43.58305812])

In [14]:
times.sum()

190.10525250434875

In [15]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=False)
iterative_searcher = IterativeSearcher(adv_sampler)

In [16]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, save_results=False)

100%|██████████| 5/5 [13:38<00:00, 163.71s/it]

CPU times: total: 6min 6s
Wall time: 13min 38s


In [17]:
modularities

array([0.69284181, 0.69864916, 0.68312082, 0.6800909 , 0.69801793])

In [18]:
times

array([150.76906037, 170.34411979, 169.89631033, 165.60446572,
       161.90343213])

In [19]:
times.sum()

818.517388343811