In [1]:
from iterative_searcher import IterativeSearcher

from Qommunity.samplers.hierarchical.advantage_sampler import AdvantageSampler
from Qommunity.searchers.hierarchical_community_searcher import (
    HierarchicalCommunitySearcher,
)

import networkx as nx
import numpy as np

In [2]:
import os


dir = f"output/"
os.makedirs(os.path.dirname(dir), exist_ok=True)

In [3]:
G = nx.karate_club_graph()

### Hierarchical

#### Basic usage

- Example of Advantage sampler usage with clique embedding:

In [4]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=True)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

In [5]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-karate")

100%|██████████| 5/5 [00:40<00:00,  8.08s/it]

CPU times: total: 9.88 s
Wall time: 40.4 s


In [6]:
communities

array([list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]])],
      dtype=object)

In [7]:
modularities

array([0.44018103, 0.44018103, 0.44018103, 0.44018103, 0.44018103])

In [8]:
times

array([7.8029716 , 8.05719256, 8.43407965, 7.84661531, 8.25471497])

- Example of Advantage sampler usage without standard embedding approach:

In [9]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=False)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

In [11]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-karate-2")

100%|██████████| 5/5 [01:03<00:00, 12.79s/it]

CPU times: total: 23.5 s
Wall time: 1min 3s


In [12]:
communities

array([list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]])],
      dtype=object)

In [13]:
modularities

array([0.44018103, 0.44018103, 0.44018103, 0.44018103, 0.44018103])

In [14]:
times

array([12.06314325, 10.28225684, 13.89440346, 16.99917865, 10.70184374])

#### Extended sampleset info
- contains communities, modularities, times, division trees and division modularities

In [15]:
sampleset = iterative_searcher.run_with_full_sampleset_info(num_runs=5)

100%|██████████| 5/5 [01:06<00:00, 13.37s/it]


In [16]:
sampleset

rec.array([(list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]), 0.44018103, 13.23299122, list([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]], [[8, 14, 15, 18, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33], [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 16, 17, 19, 21]], [[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]]), list([0.0, 0.3998332115215232, 0.44018103109012197])),
           (list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]), 0.44018103, 16.01342702, list([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]], [[8, 14, 15, 18, 20, 22, 23, 24, 25, 26, 27, 

In [17]:
sampleset.communities

array([list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]]),
       list([[23, 24, 25, 27, 28, 31], [8, 14, 15, 18, 20, 22, 26, 29, 30, 32, 33], [4, 5, 6, 10, 16], [0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21]])],
      dtype=object)

In [18]:
sampleset.modularity

array([0.44018103, 0.44018103, 0.44018103, 0.44018103, 0.44018103])

In [19]:
sampleset.time

array([13.23299122, 16.01342702, 10.89804173, 14.11864519, 12.59225225])

In [20]:
sampleset.division_modularities

array([list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197]),
       list([0.0, 0.3998332115215232, 0.44018103109012197])], dtype=object)

## Regular

In [21]:
from Qommunity.samplers.regular.leiden_sampler import LeidenSampler
from Qommunity.searchers.community_searcher import CommunitySearcher
from iterative_searcher import IterativeSearcher

import networkx as nx

In [22]:
G = nx.karate_club_graph()

In [23]:
searcher = CommunitySearcher(LeidenSampler(G))
iterative_searcher = IterativeSearcher(searcher)

In [24]:
communities, modularities, times = iterative_searcher.run(num_runs=100)

100%|██████████| 100/100 [00:00<00:00, 546.63it/s]


In [25]:
modularities

array([0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490358,
       0.44490358, 0.44490358, 0.44490358, 0.44490358, 0.44490

In [26]:
times

array([0.00600195, 0.00100017, 0.00100207, 0.00099969, 0.        ,
       0.00099969, 0.00100183, 0.00100088, 0.        , 0.00100136,
       0.00100708, 0.00100088, 0.00100207, 0.00099707, 0.00099683,
       0.00099969, 0.        , 0.00100231, 0.        , 0.00099611,
       0.00100088, 0.        , 0.0010004 , 0.        , 0.00101447,
       0.        , 0.        , 0.0010004 , 0.        , 0.00100017,
       0.00100231, 0.00100017, 0.00100136, 0.00100017, 0.00100017,
       0.        , 0.00100064, 0.        , 0.00099754, 0.00099993,
       0.00099993, 0.00100398, 0.0010004 , 0.00100064, 0.        ,
       0.00099969, 0.00100136, 0.0010004 , 0.00099897, 0.        ,
       0.00100112, 0.        , 0.00099993, 0.00100064, 0.00099707,
       0.        , 0.0010004 , 0.00099516, 0.00100088, 0.00099993,
       0.00100231, 0.00100112, 0.00099969, 0.        , 0.00100064,
       0.        , 0.00101209, 0.00097966, 0.        , 0.00099611,
       0.00100136, 0.0009985 , 0.00100207, 0.00100064, 0.     

## Sample usecase

- Comparison of use_clique_embedding=True and False on a graph of 90 nodes

In [27]:
G = nx.powerlaw_cluster_graph(n=90, m=1, p=0.2)

In [28]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=True)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

In [29]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-powerlaw_90")

100%|██████████| 5/5 [02:49<00:00, 33.81s/it]

CPU times: total: 56.5 s
Wall time: 2min 49s


In [30]:
modularities

array([0.76833733, 0.7658124 , 0.76568615, 0.76757985, 0.77654337])

In [31]:
times

array([26.56346345, 33.01482844, 31.85231853, 31.55296373, 46.0393889 ])

In [32]:
adv_sampler = AdvantageSampler(G, num_reads=100, use_clique_embedding=False)
searcher = HierarchicalCommunitySearcher(adv_sampler)
iterative_searcher = IterativeSearcher(searcher)

In [33]:
%time communities, modularities, times = iterative_searcher.run(num_runs=5, saving_path=dir+"/adv-powerlaw_90")

100%|██████████| 5/5 [09:26<00:00, 113.34s/it]

CPU times: total: 7min 10s
Wall time: 9min 26s


In [35]:
modularities

array([0.7439086 , 0.76164626, 0.7693473 , 0.75160965, 0.76448681])

In [36]:
times

array([162.53538895, 108.30013967,  99.48476887,  83.89677119,
       112.45903277])